=== karolinasuchecka/orphidys/src/introducteur_NP.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT LexicalRessource (GlobalInformation,Lexicon)>
<!ATTLIST LexicalRessource>

<!ELEMENT GlobalInformation EMPTY>
<!ATTLIST GlobalInformation
  characterCoding NMTOKEN #REQUIRED
  entrySource CDATA #REQUIRED
  languageCoding CDATA #REQUIRED
  resourceName NMTOKEN #REQUIRED
  version CDATA #REQUIRED>

<!ELEMENT Lexicon (placeName|persName|orgName|objetName)+>
<!ATTLIST Lexicon
  languageIdentifier NMTOKEN #REQUIRED
  script NMTOKEN #REQUIRED>

<!ELEMENT placeName (w)+>
<!ATTLIST placeName
  xml:id ID #REQUIRED
  ana (méronyme|synonyme|hyperonyme|métaphorique|ancien) #IMPLIED
  join (true) #IMPLIED 
  sameAs (administration|air|armée|culture|éducation|nature|navigation|règne|religion|science|société|technologie) #IMPLIED
  subtype (urbain|enfer|rural|habitat|bord|mort|cours|étendue|île|région|supranational|pays|direction) #IMPLIED
  type (commune|édifice|abstrait|souterrain|territoire|terre_mer|voie|meuble|agricole|astronyme|délimiteur|destination|forestier|hydronyme|oronyme) #REQUIRED>
<!--Les types et les subtypes se repartissent de manière suivante : 
abstrait -> enfer?
commune -> (urbain|rural)?
délimiteur -> (bord|direction)?
destination -> habitat?
édifice -> (habitat|bord|mort)?
forestier, voie -> (urbain|rural)?
hydronyme -> (cours|étendue)?
oronyme -> bord?
souterrain -> enfer?
terre_merr -> (ile|bord)?
territoire -> (supranational|région|pays)?-->

<!ELEMENT persName (w)+>
<!ATTLIST persName
 xml:id ID #REQUIRED
 ana (méronyme|synonyme|hyperonyme|métaphorique|ancien|familier) #IMPLIED
 join (true) #IMPLIED
 sameAs (administration|âme|amour|armée|arts|construction|éducation|littérature|magie|musique|nature|navigation|règne|religion|science|société|technologie) #IMPLIED
 type (homme|créature|dieu|général) #REQUIRED
 corresp (profession|fonction|statut|titre|parenté|partie|liaison|classe|nationalité) #IMPLIED
 synch (ancêtre|descendant|frère) #IMPLIED
 subtype (enfer|fictif|adversaire|allié|corps|mort) #IMPLIED>
<!-- Il y a quelques attributs qui vont ensemble :
@corresp=parenté + @synch
@corresp=liaison + @sameAs=amour
@subtype=corps + @corresp=partie + @ana=méronyme
-->
<!ELEMENT orgName (w)+>
<!ATTLIST orgName
 xml:id ID #REQUIRED
 type (fête|manifestation|tradition|histoire|météorologie) #REQUIRED
 sameAs (religion) #IMPLIED
 ana (méronyme|synonyme|hyperonyme|métaphorique|ancien|familier) #IMPLIED
 corresp (statut) #IMPLIED>
 
<!ELEMENT objetName (w)+>
<!ATTLIST objetName
 xml:id ID #REQUIRED
 type (œuvre|vaisseau) #REQUIRED
 sameAs (littérature|arts|musique|navigation|religion) #IMPLIED
 ana (méronyme|synonyme|hyperonyme|métaphorique|ancien|familier) #IMPLIED>
 
<!ELEMENT w (#PCDATA)>
<!ATTLIST w
  msd (ms|fs|mp|fp|mfs|mfp|msp|fsp) #REQUIRED
  pos (NOM|NAM) #REQUIRED
  select (coll) #IMPLIED
  xml:lang (oFR) #IMPLIED>

=== karolinasuchecka/orphidys/src/BD_NOM.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE LexicalRessource SYSTEM "introducteur_NP.dtd">

<LexicalRessource>
    <GlobalInformation languageCoding="fra" characterCoding="UTF-8" entrySource="ProLMF Democrat" resourceName="orphidys" version="1"/>

    <Lexicon languageIdentifier="fra" script="latn">
        <placeName type="commune" xml:id="arrondissement" subtype="urbain" sameAs="administration">
            <w pos="NOM" msd="ms">arrondissement</w>
            <w pos="NOM" msd="mp">arrondissements</w>
        </placeName>
        <placeName type="commune" xml:id="capitale" subtype="urbain" sameAs="administration">
            <w pos="NOM" msd="fs">capitale</w>
            <w pos="NOM" msd="fp">capitales</w>
        </placeName>
        <placeName type="commune" xml:id="chef_lieu" subtype="urbain" sameAs="administration">
            <w pos="NOM" msd="ms">chef-lieu</w>
            <w pos="NOM" msd="mp">chefs-lieux</w>
        </placeName>
        <placeName type="commune" xml:id="district" subtype="urbain" sameAs="administration" ana="méronyme">
            <w pos="NOM" msd="ms">district</w>
            <w pos="NOM" msd="mp">districts</w>
        </placeName>
        <placeName type="commune" xml:id="municipalite" subtype="urbain" sameAs="administration">
            <w pos="NOM" msd="fs">municipalité</w>
            <w pos="NOM" msd="fp">municipalités</w>
        </placeName>
        <placeName type="édifice" xml:id="ambassade" sameAs="administration">
            <w pos="NOM" msd="fs">ambassade</w>
            <w pos="NOM" msd="fp">ambassades</w>
        </placeName>
        <placeName type="édifice" xml:id="bureau" sameAs="administration" ana="méronyme">
            <w pos="NOM" msd="ms">bureau</w>
            <w pos="NOM" msd="mp">bureaux</w>
        </placeName>
        <placeName type="édifice" xml:id="cachot" sameAs="administration">
            <w pos="NOM" msd="ms">cachot</w>
            <w pos="NOM" msd="mp">cachots</w>
        </placeName>
        <placeName type="édifice" xml:id="halle" sameAs="administration">
            <w pos="NOM" msd="fs">halle</w>
            <w pos="NOM" msd="fp">halles</w>
        </placeName>
        <placeName type="édifice" xml:id="magasin" sameAs="administration">
            <w pos="NOM" msd="ms">magasin</w>
            <w pos="NOM" msd="mp">magasins</w>
        </placeName>
        <placeName type="édifice" xml:id="mairie" sameAs="administration">
            <w pos="NOM" msd="ms">mairie</w>
            <w pos="NOM" msd="mp">mairies</w>
        </placeName>
        <placeName type="édifice" xml:id="marche" sameAs="administration">
            <w pos="NOM" msd="ms">marché</w>
            <w pos="NOM" msd="mp">marchés</w>
        </placeName>
        <placeName type="édifice" xml:id="office" sameAs="administration" ana="méronyme">
            <w pos="NOM" msd="ms">office</w>
            <w pos="NOM" msd="mp">offices</w>
        </placeName>
        <placeName type="édifice" xml:id="parlement" sameAs="administration">
            <w pos="NOM" msd="ms">parlement</w>
            <w pos="NOM" msd="mp">parlements</w>
        </placeName>
        <placeName type="édifice" xml:id="poste" sameAs="administration">
            <w pos="NOM" msd="fs">poste</w>
            <w pos="NOM" msd="fp">postes</w>
        </placeName>
        <placeName type="édifice" xml:id="prefecture" sameAs="administration">
            <w pos="NOM" msd="fs">préfecture</w>
            <w pos="NOM" msd="fp">préfectures</w>
        </placeName>
        <placeName type="édifice" xml:id="prison" sameAs="administration">
            <w pos="NOM" msd="fs">prison</w>
            <w pos="NOM" msd="fp">prisons</w>
        </placeName>
        <placeName type="édifice" xml:id="refuge" sameAs="administration">
            <w pos="NOM" msd="ms">refuge</w>
            <w pos="NOM" msd="mp">refuges</w>
        </placeName>
        <placeName type="édifice" xml:id="tribunal" sameAs="administration">
            <w pos="NOM" msd="ms">tribunal</w>
            <w pos="NOM" msd="mp">tribunaux</w>
        </placeName>
        <placeName type="abstrait" xml:id="ciel" sameAs="air">
            <w pos="NOM" msd="ms">ciel</w>
            <w pos="NOM" msd="mp">cieux</w>
            <w pos="NOM" msd="mp">ciels</w>
            <w pos="NOM" msd="mp" xml:lang="oFR">cieulx</w>
            <w pos="NOM" msd="mp" xml:lang="oFR">cielz</w>
        </placeName>

        <placeName type="édifice" xml:id="base" sameAs="armée">
            <w pos="NOM" msd="fs">base</w>
            <w pos="NOM" msd="fp">bases</w>
        </placeName>
        <placeName type="édifice" xml:id="camp" sameAs="armée">
            <w pos="NOM" msd="ms">camp</w>
            <w pos="NOM" msd="mp">camps</w>
        </placeName>
        <placeName type="édifice" xml:id="forteresse" sameAs="armée">
            <w pos="NOM" msd="fs">forteresse</w>
            <w pos="NOM" msd="fp">forteresses</w>
        </placeName>
        <placeName type="édifice" xml:id="sentinelle" sameAs="armée">
            <w pos="NOM" msd="fs">sentinelle</w>
            <w pos="NOM" msd="fp">sentinelles</w>
        </placeName>
        <placeName type="édifice" xml:id="siege" sameAs="armée">
            <w pos="NOM" msd="ms">siège</w>
            <w pos="NOM" msd="mp">sièges</w>
        </placeName>
        <placeName type="édifice" xml:id="tour" sameAs="armée">
            <w pos="NOM" msd="fs">tour</w>
            <w pos="NOM" msd="fp">tours</w>
        </placeName>
        <placeName type="souterrain" xml:id="tranchee" sameAs="armée">
            <w pos="NOM" msd="fs">tranchée</w>
            <w pos="NOM" msd="fp">tranchées</w>
        </placeName>
        <placeName type="édifice" xml:id="foire" sameAs="culture">
            <w pos="NOM" msd="ms">foire</w>
            <w pos="NOM" msd="mp">foires</w>
        </placeName>
        <placeName type="édifice" xml:id="galerie" sameAs="culture">
            <w pos="NOM" msd="fs">galerie</w>
            <w pos="NOM" msd="fp">galeries</w>
        </placeName>
        <placeName type="édifice" xml:id="musee" sameAs="culture">
            <w pos="NOM" msd="ms">musée</w>
            <w pos="NOM" msd="mp">musées</w>
        </placeName>
        <placeName type="édifice" xml:id="academie" sameAs="éducation">
            <w pos="NOM" msd="fs" select="coll">académie</w>
            <w pos="NOM" msd="fp" select="coll">académies</w>
        </placeName>
        <placeName type="édifice" xml:id="college" sameAs="éducation">
            <w pos="NOM" msd="ms">collège</w>
            <w pos="NOM" msd="mp">collèges</w>
        </placeName>
        <placeName type="édifice" xml:id="ecole" sameAs="éducation">
            <w pos="NOM" msd="ms">école</w>
            <w pos="NOM" msd="mp">écoles</w>
            <w pos="NOM" msd="ms" xml:lang="oFR">escole</w>
            <w pos="NOM" msd="mp" xml:lang="oFR">escoles</w>
        </placeName>
        <placeName type="édifice" xml:id="universite" sameAs="éducation">
            <w pos="NOM" msd="fs">université</w>
            <w pos="NOM" msd="fp">universités</w>
        </placeName>
        <placeName type="territoire" xml:id="habitat" sameAs="nature">
            <w pos="NOM" msd="ms">habitat</w>
            <w pos="NOM" msd="mp">habitats</w>
        </placeName>
        <placeName type="territoire" xml:id="paysage" sameAs="nature">
            <w pos="NOM" msd="ms">paysage</w>
            <w pos="NOM" msd="mp">paysages</w>
        </placeName>
        <placeName type="territoire" xml:id="plage" sameAs="nature">
            <w pos="NOM" msd="fs">plage</w>
            <w pos="NOM" msd="fp">plages</w>
        </placeName>
        <placeName type="territoire" xml:id="plaine" sameAs="nature">
            <w pos="NOM" msd="fs">plaine</w>
            <w pos="NOM" msd="fp">plaines</w>
        </placeName>
        <placeName type="territoire" xml:id="prairie" sameAs="nature">
            <w pos="NOM" msd="fs">prairie</w>
            <w pos="NOM" msd="fp">prairies</w>
        </placeName>
        <placeName type="territoire" xml:id="pre" sameAs="nature">
            <w pos="NOM" msd="fs">pré</w>
            <w pos="NOM" msd="fp">prés</w>
            <w pos="NOM" msd="fs" xml:lang="oFR">pre</w>
            <w pos="NOM" msd="fp" xml:lang="oFR">pres</w>
            <w pos="NOM" msd="fp" xml:lang="oFR">préz</w>
        </placeName>
        <placeName type="territoire" xml:id="savane" sameAs="nature">
            <w pos="NOM" msd="fs">savane</w>
            <w pos="NOM" msd="fp">savanes</w>
        </placeName>
        <placeName type="territoire" xml:id="site" sameAs="nature" ana="hyperonyme">
            <w pos="NOM" msd="ms">site</w>
            <w pos="NOM" msd="mp">sites</w>
        </placeName>
        <placeName type="terre_mer" xml:id="port" sameAs="navigation">
            <w pos="NOM" msd="ms">port</w>
            <w pos="NOM" msd="mp">ports</w>
        </placeName>
        <placeName type="voie" xml:id="pont" sameAs="navigation">
            <w pos="NOM" msd="ms">pont</w>
            <w pos="NOM" msd="mp">ponts</w>
        </placeName>
        <placeName type="voie" xml:id="quai" sameAs="navigation">
            <w pos="NOM" msd="ms">quai</w>
            <w pos="NOM" msd="mp">quais</w>
        </placeName>
        <placeName type="édifice" xml:id="chateau" sameAs="règne">
            <w pos="NOM" msd="ms">château</w>
            <w pos="NOM" msd="mp">châteaux</w>
        </placeName>
        <placeName type="édifice" xml:id="palais" sameAs="règne">
            <w pos="NOM" msd="msp">palais</w>
        </placeName>
        <placeName type="meuble" xml:id="trone" sameAs="règne">
            <w pos="NOM" msd="ms">trône</w>
            <w pos="NOM" msd="mp">trônes</w>
            <w pos="NOM" msd="ms" xml:lang="oFR">trosne</w>
            <w pos="NOM" msd="mp" xml:lang="oFR">trosnes</w>
        </placeName>
        <placeName type="abstrait" xml:id="paradis" sameAs="religion" ana="métaphorique">
